name: Java CI , Gradle

on:
  push:
    branches: [ "main" ]
    # main 브랜치에 push or pullrequest가 merge 될 시 동작한다.

#jobs - 하나이상의 작업을 정한다. 병렬로 수행될수있음.
jobs:
  #deploy - job name
  deploy:
  #ubuntu-latest 리눅스 (우분투) 환경에서 실행
    runs-on: ubuntu-latest

  #deploy job 안에서 실행될 단계들 작성
    steps:
  # 소스코드 체크아웃 후 java21 설치
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
  # gradle 빌드를 위해 ./gradlew 파일의 권한 설정
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
        # +x --> 실행권한 부여
  # java 빌드
      - name: Spring boot Build
        run: ./gradlew clean build
  # Docker image build , Dockerfile 기반으로 Docker image 빌드
      - name: docker image Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/rizing-camp-ci-cd .
  # Docker hub 로그인 - 도커허브에 이미지를 푸쉬하기 위함.
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: image push to docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME}}/rizing-camp-ci-cd